Scandit/barcodescanner-sdk-cordova

- docs/Scandit.java
- docs/cropped-or-scaled-picker.md
- docs/examples.md
- docs/restrict-scanning-area.md
Since there was a bit of a mess with the documentation changes (because of the reset), I went through my old repo and looked for all the changes that were not commited yet
> Improvment to documentation

- docs/guides-cordova.md
- docs/telerik.md
Under Telerik everything works and should be quite straightforward.
I added the caveats that I found noteworthy.
> Added documentation for telerik platform

- src/ios/SBSConstraints.h
Added `#import <CoreGraphics/CoreGraphics.h>` to SBSConstraints.h
> Import CoreGraphics as it's needed in order to use CGRect

- docs/Scandit.java
- plugin.xml
- src/callbacks.js
- src/textrecognitionsettings.js
and changed the show(callbacks) documentation to move away from the block of text.
> Added a text recognition settings object

- plugin.xml
- src/barcodepicker.js
- src/ios/SBSTypeConversion.h
- src/ios/SBSTypeConversion.m
- src/ios/SBSUIParamParser.m
- src/ios/ScanditSDK.mm
- src/matrixScanSession.js
- src/overlay.js
- src/settings.js
@moritz-scandit can you do squash and merge when done? ☺️
> Matrix Scan (JS + iOS)

- docs/Scandit.java
Added an invisible method to force doxygen to generate a page for SymbologySettings class.
> Force doxygen to generate a page for SymbologySettings class

- docs/Scandit.java
Made a fix in the documentation for ScanSettings.scanningHotSpot field.
> Corrected a small error in the docs

- samples/extended/readme.md
(cherry picked from commit a22b53f2585fda4918f53d9e4bfbcce75af6e4f1)
> Slightly adjusted the readme.md

- src/ios/ScanditSDK.mm
Fix an issue where the WKWebView thread is blocked indefinitely sometimes if the scanner is presented modally and the cordova-plugin-wkwebview-engine plugin is used
> Fix an issue where the WKWebView thread is blocked indefinitely sometimes

- samples/matrixscan/www/index.html
[SDK-6799](https://jira.scandit.com/browse/SDK-6799)
> remove usage of didScan from MatrixScan sample

- src/ios/ScanditSDK.mm
Adjust the calls to the didProcess method such that it is no longer called any time a code is being tracked while matrix scan is enabled but only if a new code has started to be tracked
> Adjust call to didProcessFrame to improve performance of matrixscan

- plugin.xml
- src/ios/SBSTrackedCode+Private.h
- src/ios/SBSTypeConversion.m
- src/ios/ScanditSDK.mm
Signed-off-by: Tibor Molnár <tibor@scandit.com>
> [SDK-8230] Fix MatrixScan rejection

- src/settings.js
Signed-off-by: Petra Donka <petra@scandit.com>
> add default code32 settings

- plugin.xml
- src/android/com/mirasense/scanditsdk/plugin/BarcodePickerWithSearchBar.java
- src/android/com/mirasense/scanditsdk/plugin/ScanditCordovaTopView.java
- src/android/com/mirasense/scanditsdk/plugin/SubViewPickerController.java
to control where the picker is added.
> Fixed a logic error in constraints. Added the ScanditCordovaTopView.

- docs/Scandit.java
- src/settings.js
Also removed camera2 disabling from properties (why was it even there?).
> Added recognition mode for code and text. Fixed properties doc.

- samples/ionic-sample/README.md
Content/text approved by Iciar
> SDK-10964 - Ionic sample description

- samples/ionic-sample/README.md
> Cherry Pick #229 - ionic sample description

- types/index.d.ts
Signed-off-by: Petra Donka <petra@scandit.com>
> SDK-9689 improved d.ts

- src/ios/SBSScanCasePlugin.m
- src/ios/SBSTypeConversion.h
- src/ios/SBSTypeConversion.m
- src/ios/ScanditSDK.mm
- Barcode’s `location` and `convertedLocation`
- TrackedBarcode’s `predictedLocation` and `convertedPredictedLocation`
> Expose barcode's location

- src/android/com/mirasense/scanditsdk/plugin/PickerControllerBase.java
…for cases where javascript doesn't call the native function anymore after the callback is over.
> [SDC-976] ANR fix through lock timeout

- src/android/com/mirasense/scanditsdk/plugin/FullScreenPickerActivity.java
(cherry picked from commit 83ee04dab6c59df2c2f5236cd7dff2265ca58f3c)
> Fixed a potential deadlock when stopping through the back button.

- docs/Scandit.java
- samples/simple/www/index.html
- src/barcode.js
- src/settings.js
Reverts Scandit/barcodescanner-sdk-cordova#261
> Revert "SDC-2652 — Add IATA 2 of 5"

- src/android/com/mirasense/scanditsdk/plugin/FullScreenPickerActivity.java
- src/android/com/mirasense/scanditsdk/plugin/SubViewPickerController.java
(cherry picked from commit 8bcc80a07f9edd2195db25562ba5049bde7113e4)
> [Cherry-Pick] Guarding against activity and state machine nullpointers.
